[package]
name = "gpu-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
lazy_static = "1.4.0"
macros = { path = "macros" }
pollster = "0.3.0"
vello = "0.2.0"
wgpu = "0.20.1"
winit = "0.30.2"
